package comiam.chat.client.connection.message;

public enum RequestType
{
    SIGN_IN_MESSAGE,
    SIGN_UP_MESSAGE,
    GET_CHATS_MESSAGE,
    GET_USERS_OF_CHAT_MESSAGE,
    GET_ONLINE_USERS_OF_CHAT_MESSAGE,
    GET_MESSAGES_FROM_CHAT_MESSAGE,
    SEND_MESSAGE_MESSAGE,
    CREATE_CHAT_MESSAGE,
    CONNECT_TO_CHAT_MESSAGE,
    DISCONNECT_MESSAGE
}
