package org.nsu.fit.tests.api;

import io.qameta.allure.Feature;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import org.nsu.fit.services.log.Logger;
import org.nsu.fit.services.rest.RestClient;
import org.nsu.fit.services.rest.data.AccountTokenPojo;
import org.nsu.fit.services.rest.data.CustomerPojo;
import org.nsu.fit.services.rest.data.PlanPojo;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.io.IOException;
import java.util.List;

public class GetCustomerPlansTest {
    private AccountTokenPojo adminToken;
    RestClient client;
    CustomerPojo customerPojo;

    @BeforeClass
    public void createCustomer() {
        client = new RestClient();
        adminToken = client.authenticate("admin", "setup");
        customerPojo = client.createAutoGeneratedCustomer(adminToken);
    }

    @Test(description = "Get user plans as admin")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Get all plans")
    public void getPlansAsAdmin() throws IOException {
        List<PlanPojo> plans = client.getUserPlans(adminToken, customerPojo.id);
        Logger.debug("Admin plans: " + Logger.toJson(plans));
    }

    @Test(description = "Get user plans as user")
    @Severity(SeverityLevel.BLOCKER)
    @Feature("Get all plans")
    public void getPlansAsCustomer() throws IOException {
        AccountTokenPojo token = new RestClient().authenticate(customerPojo.login, customerPojo.pass);
        List<PlanPojo> plans = client.getAvailablePlans(token);
        Logger.debug("User plans: " + Logger.toJson(plans));
    }
}
